package dev.gitgotchi.databinding

import android.view.LayoutInflater
import android.view.View
import androidx.viewbinding.ViewBinding
import com.google.android.material.button.MaterialButton
import android.widget.TextView
import dev.gitgotchi.R

/**
 * Generated ViewBinding class for activity_main.xml
 * This is typically auto-generated by Android Gradle Plugin.
 * Creating manually for initial setup.
 */
class ActivityMainBinding private constructor(
    private val rootView: View
) : ViewBinding {
    
    val titleText: TextView = rootView.findViewById(R.id.titleText)
    val subtitleText: TextView = rootView.findViewById(R.id.subtitleText)
    val btnStartOverlay: MaterialButton = rootView.findViewById(R.id.btnStartOverlay)
    val btnSettings: MaterialButton = rootView.findViewById(R.id.btnSettings)
    val btnCharacterSelect: MaterialButton = rootView.findViewById(R.id.btnCharacterSelect)
    
    override fun getRoot(): View = rootView
    
    companion object {
        fun inflate(inflater: LayoutInflater): ActivityMainBinding {
            val view = inflater.inflate(R.layout.activity_main, null, false)
            return ActivityMainBinding(view)
        }
    }
}
